environment: production

# Volume and logging configuration
volume: /opt/bgpalerter
logging:
  directory: logs
  outputLogs: true
  rotate:
    enabled: true
    maxSize: 10MB
    maxFiles: 5

# Monitors
monitors:
  rpki:
    enabled: true
    file: rpki.yml

  statics:
    enabled: true
    monitoredPrefixesFiles:
      - prefixes.yml

  groups:
    enabled: true
    file: groups.yml

# Notifications
notifications:
  enabled: false
  file: subs.yml

# Optional settings
otherSettings:
  refreshInterval: 300
