version: "3.9"

services:
  bgpalerter:
    image: bgpalerter-local   # Use the local image built from the Dockerfile
    container_name: bgpalerter
    restart: always
    volumes:
      - ./config:/opt/bgpalerter/config:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"




