services:
  bgpalerter:
    image: bgpalerter/bgpalerter:2.0.1
    container_name: bgpalerter
    restart: always
    volumes:
      - ./config:/opt/bgpalerter/config:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"





